server:
  port: 8388

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
       
# Oracle Connect
# Datasource Bean 생성
  datasource:
   driver-class-name: oracle.jdbc.driver.OracleDriver
   url: jdbc:oracle:thin:@localhost:1521/xe
   username: person01
   password: tiger
    
  
  #Jpa Setting
  jpa:
    # database-platform: org.hibernate.dialect.OracleDialect  # Jpa사용시 11g에 대한 방언 설정 --> Paging 작업 
    show-sql: true
    hibernate:
      ddl-auto: update
 
  # View Resolver --> jsp
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # gmail Transfer 
  mail:
    host: smtp.gmail.com
    port: 587
    username: ttaekwang3@gmail.com
    password: nfnc dras  
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true  
          
 
      
logging.level:
  org.hibernate.SQL: debug   # logger를 통해 하이버네이트 실행 SQL 
  
# Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml 
  
#upload Folder
com.oracle.oBootBoard03.upload.path: upload   
  


  
  
  
  
  
  
  
  
  
  
  
  
              