server:
  port: 0
# Oracle Connect
spring:
  application:
    name: user-service01
    
eureka:
  instance:
    # 알아서 만들어 주는 id
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    # 클라이언트가 유레카 서비스에 자신을 등록
    register-with-eureka: true
    # 레지스트리 정보를 클라이언트 로컬에 캐싱함. 유레카 클라이언트가 유레카 서비스에 등록시 설정 가능
    fetch-registry: true
    service-url:
      # 서버의 IP:PORT
      defaultZone: http://127.0.0.1:8761/eureka/

greeting:
  message: welcom to MSA