server:
  port: 8481
# Oracle Connect
spring:
# Datasource Bean 생성
  datasource:
   driver-class-name: oracle.jdbc.driver.OracleDriver
   #  docker  
   # url: jdbc:oracle:thin:@172.30.1.13:1521/xe
   url: jdbc:oracle:thin:@127.0.0.1:1521/xe
   username: scottJpa
   password: tiger
    
  
  #Jpa Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
 
 
      
logging.level:
  org.hibernate.SQL: debug   # logger를 통해 하이버네이트 실행 SQL 
  
# Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml 
  
  
#upload Folder
com.oracle.oBootTodoApi01.upload.path: upload  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
              